# -*- coding: utf-8 -*-
"""Car License Detection using Yolo v10 custom training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lC6oJ0FCMykk5mr9g_c7TfvePpPs69tI
"""

!nvidia-smi

!git clone https://github.com/THU-MIG/yolov10.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov10

!pwd

!pip install .

import os
import urllib.request

# Create a directory for the weights in the current working directory
weights_dir = os.path.join(os.getcwd(), "weights")
os.makedirs(weights_dir, exist_ok=True)

# URLs of the weight files
urls = [
    "https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10n.pt",
    "https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10s.pt",
    "https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10m.pt",
    "https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10b.pt",
    "https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10x.pt",
]

# Download each file
for url in urls:
    file_name = os.path.join(weights_dir, os.path.basename(url))
    urllib.request.urlretrieve(url, file_name)
    print(f"Downloaded {file_name}")

!unzip license_data.zip

!yolo task=detect mode=train epochs=100 batch=16 plots=True model=weights/yolov10n.pt data=data.yaml

!yolo task=detect mode=predict conf=0.25 save=True model=runs/detect/train/weights/best.pt source=car.jpg

!yolo task=detect mode=predict conf=0.25 save=True model=runs/detect/train/weights/best.pt source=video.mp4

